version: '3'

services:
  jibber-jabber-auth:
    image: jibber-jabber-auth
    container_name: jibber-jabber-auth
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - 8081:8080
    env_file:
      - auth.env
  jibber_jabber_auth_db:
    container_name: jibber_jabber_auth_db
    image: postgres:12
    ports:
      - 5433:5432
    env_file:
      - database.env
    volumes:
      - jjauth:/var/lib/postgresql/data
volumes:
  jjauth:
    external: true